### ISSUE TITLE
Add color back again?

### ISSUE THREAD

**Issue by jgrizou** [poppy-project/poppy-simu#3]
I implemented the ability to change color in the first place so users can customize their robot a bit, feel more like it is theirs (Ideally we would like to store the color in the localstorage.). Why has it been removed?

**Comment by show0k** [comment]
Because @damiencaselli don't like the pink !
But i agree with you that customisation can improve motivation of users.

**Comment by ghost** [comment]
May be one day we will be able to edit the whole robot, but for now I chose to remove all the extra stuff not requested explicitly by our users until we have decent feedback on the viewer.

Since changing color is a feature that is, at the moment, not used in any kind of educational activity, I applied the above rule.

> customisation can improve motivation of users

Yep, and I badly want to add a texture selector to the ground plan.
But :notes: what is it good for? Absolutely nothing :notes: 
For now, that would also not really be useful to the end-user, may be even hinder the understanding of the webapp.

Adding gizmos and extra features drives to lose focus on the main functionality, and as long as we don't have any feedback on it, the viewer purpose should be - in my opinion - to view the robot.

**Comment by jgrizou** [comment]
Fair enough
